### ISSUE TITLE
Dimensions are interchanged when used to create filematrix object from a csv file

### ISSUE THREAD

**Issue by shawnbrar** [andreyshabalin/filematrix#7]
I am trying to read data from a csv file using `fm.create.from.text.file()` function. Below is my my code:-

`fc <- fm.create.from.text.file("./RELIANCE.NS.csv", "fc", omitCharacters = "null", delimiter = ",", type = "double", skipRows = 1, skipColumns = 1)`

I am using the file in this zip:- [RELIANCE.NS.zip](https://github.com/andreyshabalin/filematrix/files/5223407/RELIANCE.NS.zip).
It is not a very big file. But I just wanted to get to know the implementation.

When I am using the above code, the dimensions of my data get interchanged ie my data is of `6156` **columns** and `6` **rows**. But it should actually be of `6156` **rows** and `6` **columns**.

How can I correct this??

**Comment by andreyshabalin** [comment]
Hi @shawnbrar,

It is not a bug, it's a feature. Sorry if it is not clear in the reference manual.

The `fm.create.from.text.file()` function is designed for huge files, with the aim of never loading the while file in memory.

The data in text files is stored by rows while the data in matrices is stored by columns.
For best performance, we read the text file sequentially and fill in the filematrix sequentially, thus we need to create a transposed matrix.

For your purposes, you can just load the text file (`data.table::fread()` is a fast option) and create a filematrix from the loaded matrix. This will not make it transposed.

Hope this helps.

Andrey
